version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: investment
    ports:
      - '3000:3000'
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: postgres:13-alpine
    container_name: investment-postgres-db
    env-file:
      - .env
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
